name: "Deploy Container and NPM package"

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone
        uses: actions/checkout@v2
      -
        name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - 
        name: Fetch dependencies
        run: npm install
      -
        name: Run Tests
        run: npm test
      -
        name: Show Compose Log on Error
        if: ${{ failure() }}
        run: cd test/bench && docker-compose logs

  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.num }}
      tag: ${{ steps.tag.outputs.truthy }}
    steps:
      -
        name: Clone
        uses: actions/checkout@v2
      -
        name: Get Version
        id: version
        run: echo ::set-output name=num::${GITHUB_REF#refs/*/}
      -
        name: Is Tag?
        id: tag
        run: echo ::set-output name=truthy::$([[ ${{ steps.version.outputs.num }} =~ ^v([0-9]+\.){2}[0-9]+[-\+].*$ ]] && echo 'true' || echo 'false')


  npm:
    if: needs.prepare.outputs.tag == 'true'
    needs:
      - test
      - prepare
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone
        uses: actions/checkout@v2
      -
        name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  docker:
    needs:
      - test
      - prepare
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push multiarch images, as :latest to ghcr.io
        run: docker buildx build --push --platform "linux/amd64,linux/arm64" --tag ghcr.io/bitmeal/rosproxy:latest .
      -
        name: Tag and push as version from tag
        if: needs.prepare.outputs.tag == 'true'
        run: docker tag ghcr.io/bitmeal/rosproxy:latest ghcr.io/bitmeal/rosproxy:${{ needs.prepare.outputs.version }} && docker push ghcr.io/bitmeal/rosproxy:${{ needs.prepare.outputs.version }}