name: "Deploy Container and NPM package"

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone
        uses: actions/checkout@v2
      -
        name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - 
        name: Fetch dependencies
        run: npm install
      - name: Run Tests
        run: npm test

  npm:
    if: github.event.ref_type == 'tag'
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone
        uses: actions/checkout@v2
      -
        name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  docker:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone
        uses: actions/checkout@v2
      -
        name: Get Version
        id: ver
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push multiarch images, as :latest to ghcr.io
        run: docker buildx build --push --platform "linux/amd64,linux/arm64" --tag ghcr.io/bitmeal/rosproxy:latest .
      -
        name: Tag and push as version from tag
        if: github.event.ref_type == 'tag'
        run: docker tag ghcr.io/bitmeal/rosproxy:latest ghcr.io/bitmeal/rosproxy:${{ steps.ver.outputs.tag }} && docker push ghcr.io/bitmeal/rosproxy:${{ steps.ver.outputs.tag }}